### ISSUE TITLE
Question: Does using this app count as "counts" on whatever site the podcast is from?

### ISSUE THREAD

**Issue by ddwwcruz** [SolarFloss/Reach-Podcast-Player#1]
Based on what I know these podcasts live off of the download count or something. That's how they tell if the podcast is doing well. Will using this app count as a download or play or something?

**Comment by lorem-ipsumm** [comment]
Hey sorry, I didn't see this. Unfortunately I'm not exactly sure if this counts as a play for their metrics. The only reason that I would assume that it does, is because it streams the episode directly from their RSS feed.
